### ISSUE TITLE
Switch to TexLive 2015

### ISSUE THREAD

**Issue by mhriemers** [sharelatex/sharelatex-docker-image#14]

**Comment by rWolstenholme** [comment]
I'm pretty clueless with docker, but to me it looks like 2015 is installed on a new image. The bit below is in the dockerfile and installs texlive, it's pointing at the latest version all the time as far as I can work out.

``` dockerfile
# Install TexLive
RUN apt-get install -y wget
RUN wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz; \
    mkdir /install-tl-unx; \
    tar -xvf install-tl-unx.tar.gz -C /install-tl-unx --strip-components=1

RUN echo "selected_scheme scheme-basic" >> /install-tl-unx/texlive.profile; \
    /install-tl-unx/install-tl -profile /install-tl-unx/texlive.profile
RUN rm -r /install-tl-unx; \
    rm install-tl-unx.tar.gz
```

edit: I think this is a problem, because the version installed does not match the path used in the dockerfile. The next line, setting the path, has 2014 hard-coded in:

``` dockerfile
ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2014/bin/x86_64-linux/
```

**Comment by Witiko** [comment]
I created [a pull request](https://github.com/Witiko/sharelatex-docker-image/pull/1) for this issue.

**Comment by henryoswald** [comment]
The new version 0.2.x is using 2015
