### ISSUE TITLE
Metric (TFM) file not found

### ISSUE THREAD

**Issue by dubov94** [sharelatex/sharelatex-docker-image#25]
Hello,

I have successfully installed all the components running the following:

```
$ docker run -d --name sharemongo mongo:2.6
$ docker run -d --name shareredis redis:latest
$ docker run -d -P -p 5000:80 -v /opt/sharelatex --env SHARELATEX_MONGO_URL=mongodb://mongo/sharelatex --env SHARELATEX_REDIS_HOST=redis --link sharemongo:mongo --link shareredis:redis --name sharelatex sharelatex/sharelatex
```

Then I created an administrator user as mentioned in README and installed full TeX Live:

```
$ docker exec sharelatex tlmgr install scheme-full
```

After it I created a new project:

```
\documentclass{article}
\usepackage[russian]{babel}

\begin{document}
Привет, мир!
\end{document}
```

But unfortunately I am getting an error that the TFM file could not be found. [Log](https://github.com/sharelatex/sharelatex-docker-image/files/56481/log.txt) contains warnings, but adding `fontenc` and `inputenc` obviously does not help.

I think it might be connected with [this issue](http://stackoverflow.com/questions/7416510/running-tex-from-php-script). How do you think?

**Comment by dubov94** [comment]
So it turned out that instead of:

```
$ docker exec sharelatex tlmgr install scheme-full
```

I could have used:

```
$ docker exec sharelatex apt-get update
$ docker exec sharelatex apt-get install -y texlive-full
```

**Comment by jazzdd86** [comment]
I have the same problem. Unfortunately installing texlive with apt-get is not an option, because of the very old texlive packages used by ubuntu included into the sharelatex image. 

With the tlmgr scheme-full installation everything works fine, except when I want to use fonts (as the OP tried with Cyrillic.

A miminal example is: 

```
\documentclass{minimal}

\usepackage{fontspec}
\usepackage{polyglossia}
\setdefaultlanguage[latesthyphen=true, babelshorthands=true]{german}
\usepackage[clock]{ifsym} % Symbolpackage zB \Interval, \Wecker etc


\begin{document}
test

\Interval

\end{document}
```

I use lualatex for compiling - if you comment out \Interval which should be a clock symbol, everything works fine.
With \Interval uncommented it throws following message

```
error (file ifclk10): Font ifclk10 at 600 not found
```

files are there 

```
/usr/local/texlive/2015/texmf-dist/tex/latex/ifsym/uifclk.fd
/usr/local/texlive/2015/texmf-dist/fonts/source/public/ifsym/ifclk.gen
/usr/local/texlive/2015/texmf-dist/fonts/source/public/ifsym/ifclk10.mf
/usr/local/texlive/2015/texmf-dist/fonts/source/public/ifsym/ifclkb10.mf
/usr/local/texlive/2015/texmf-dist/fonts/tfm/public/ifsym/ifclk10.tfm
/usr/local/texlive/2015/texmf-dist/fonts/tfm/public/ifsym/ifclkb10.tfm
```

Whats wrong with the manual texlive installation?

**Comment by blaisep** [comment]
Ummm, shouldn't you use
install-tl instead of tlmgr

IIRC, tlmgr will install packages but install-tl gets you the tlmgr to
start with.

apt-get will install old versions and not give you the granularity of
packages.

**Comment by jazzdd86** [comment]
yes, I installed my texlive distribution with the install-tl script.

BTW: the image itself conatins a small basic installation of texlive - therefore the tlmgr is already installed within the image. That is why the command written by the OP should be valid too.

**Comment by jazzdd86** [comment]
Another information concerning this issue. When I use the shell to login to the docker image with

```
docker exec -it imagename bash
```

and try to compile the minimal example above it works!!

A ifclk10.pk is written into /root/.texlive2015/... If I use this example on the offical sharelatex website, it writes this pk file into the /tmp/ directory.

So, I think it must have something to do with the sharelatex user running the sharelatex system but cannot make use of mktexpk because the home directory is missing or the system is not configured to use the tmp directory for pk file compiling.

Any thoughts?

**Comment by jazzdd86** [comment]
Found it...AAAAHHHH..this little thing had cost me hours to figure out.

As I wrote in the previous post, I thought it must have something to do with sharelatex user and priviliges. I stumbled over the adduser command in the dockerfile and the home directory. I looked there and it was owned by ROOT AND NOT SHARELATEX

So a simple 

```
chown -R sharelatex:sharelatex /var/www/sharelatex
```

was all it needed to let this problem go away!

In your production installation instructions you have this command listed, but you totally forgot it to include it in the Dockerfile.
So please include this little line in the Dockerfile and close this issue.
Thanks

**Comment by dubov94** [comment]
@jazzdd86
You are absolutely right, this was the problem.

**Comment by zarbis** [comment]
Alternatively (if everything is run under the www-data user) you should correct owner for /var/www
`chown www-data:www-data /var/www/`
In this case the folder /var/www/.texlive2016 and subfolders would be created correctly.
For an exact folder name see /var/log/sharelatex/clsi.log

**Comment by jazzdd86** [comment]
yes, with the new docker image it's /var/www and it's running with the www-data user.

But this is what keeps me wondering - because in this repository and its scripts it is always the sharelatex user running sharelatex. In the docker image on docker hub it's the www-data user....strange.

They should enable automatic build for the image to always get the latest system.

**Comment by dpq** [comment]
Also, make sure to install **lh**:

    tlmgr install lh

For some reason, it didn't get installed with the Cyrillic package collection automatically for me.

**Comment by mserranom** [comment]
We’ve merged this repository into https://github.com/overleaf/overleaf, so we’re closing all of its issues and will archive it. If this is still a problem, please open a new issue on https://github.com/overleaf/overleaf . Thanks!
